# Generated by Django 3.0.8 on 2020-08-12 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
        ('states', '0001_initial'),
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('infections', models.BigIntegerField(null=True)),
                ('active_cases', models.BigIntegerField(null=True)),
                ('new_cases', models.BigIntegerField(null=True)),
                ('new_deaths', models.BigIntegerField(null=True)),
                ('deaths', models.BigIntegerField(null=True)),
                ('samples_proccesed', models.BigIntegerField(null=True)),
                ('recovered', models.BigIntegerField(null=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on wich object was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on wich object was last updated.', verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, help_text='Date time on wich object was deleted.', verbose_name='deleted at')),
                ('city_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.City')),
                ('country_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.Country')),
                ('state_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='states.State')),
            ],
        ),
    ]
