<<<<<<< HEAD
# Generated by Django 3.0.8 on 2020-08-10 05:50
=======
# Generated by Django 3.0.8 on 2020-08-09 01:11
>>>>>>> features

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Care',
            fields=[
<<<<<<< HEAD
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which object was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on which object was last updated.', verbose_name='updated at')),
=======
>>>>>>> features
                ('care_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=4000)),
            ],
<<<<<<< HEAD
            options={
                'abstract': False,
            },
=======
>>>>>>> features
        ),
    ]
