<<<<<<< HEAD
# Generated by Django 3.0.8 on 2020-08-10 05:50
=======
# Generated by Django 3.0.8 on 2020-08-09 01:11
>>>>>>> features

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
<<<<<<< HEAD
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which object was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on which object was last updated.', verbose_name='updated at')),
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(blank=True, max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('flag', models.CharField(max_length=500)),
                ('population', models.BigIntegerField()),
=======
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on wich object was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on wich object was last updated.', verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, help_text='Date time on wich object was deleted.', verbose_name='deleted at')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], max_length=8)),
                ('flag', models.CharField(max_length=500)),
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=50)),
>>>>>>> features
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
