# Generated by Django 3.0.8 on 2020-08-07 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
        ('utils', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('recoveridmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='utils.RecoveridModel')),
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=50)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.Country')),
            ],
            bases=('utils.recoveridmodel',),
        ),
    ]
